# Generated by Django 5.2.1 on 2025-10-26 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('Cover Letter', 'Cover Letter'), ('Interview Questions', 'Interview Questions'), ('Interview Answers', 'Interview Answers'), ('Portfolio From Resume', 'Portfolio From Resume'), ('Portfolio From QNA', 'Portfolio From QNA'), ('Resume', 'Resume'), ('Resume Score', 'Resume Score'), ('Resume Keyword Gap', 'Resume Keyword Gap'), ('Resume Auto Rewrite', 'Resume Auto Rewrite'), ('Resume Skills Gap', 'Resume Skills Gap'), ('Resume Career Recommendation', 'Resume Career Recommendation')], default='Cover Letter', max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ai_analytics', related_query_name='user_ai_analytic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
