# Generated by Django 5.2.1 on 2025-11-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalytics',
            name='generation_type',
            field=models.CharField(choices=[('Cover Letter', 'Cover Letter'), ('Interview Questions', 'Interview Questions'), ('Interview Answers', 'Interview Answers'), ('Portfolio From Resume', 'Portfolio From Resume'), ('Portfolio From QNA', 'Portfolio From QNA'), ('Resume', 'Resume'), ('Resume Score', 'Resume Score'), ('Resume Keyword Gap', 'Resume Keyword Gap'), ('Resume Auto Rewrite', 'Resume Auto Rewrite'), ('Resume Skills Gap', 'Resume Skills Gap'), ('Resume Career Recommendation', 'Resume Career Recommendation'), ('Job Recommendation', 'Job Recommendation')], default='Cover Letter', max_length=50),
        ),
    ]
