# Generated by Django 5.2.1 on 2025-10-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='rss_feed',
            new_name='rss_url',
        ),
    ]
