# Generated by Django 5.2.1 on 2025-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0003_usersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='alert',
            field=models.BooleanField(default=True),
        ),
    ]
